### ISSUE TITLE
Input values

### ISSUE THREAD

**Issue by zachbatx** [SSAgov/ANDI#128]
Hello,

When focus is on an `<input type=text value=100> `using the "focusable element"  feature the value is not displayed in the accessible components or the ANDI output. 

I know the value is not usually recognized by AT when used with most components but when it is used with `<input type=text value=100>` the value is read by the screen reader. 

Would be nice to have the value displayed in the ANDI output.
example: `<input type=text value=100 aria-label=balance readonly> `
ANDI Output: "balance readonly 100"

**Comment by JohnCotterSSA** [comment]
Hi there.

ANDI will display the value in the accessibility components list and the ANDI output when the value is part of the accessible name or accessible description. For example, with input buttons `<input type=submit value=next />", the accessible name of this element is "next".

For textboxes, it doesn't include the value in the Output because that value can be changed by the user when typing in text. Since ANDI is primarily static by design, it would not react to those changes and may cause confusion about the accuracy of the value in the Output. Your suggestion is a good one, and something we've considered. As you use ANDI, you are safe to assume that the value of standard textboxes will get spoken by all screen readers.

**Comment by zachbatx** [comment]
Thank you for the reply.

Yes, in some cases the value is displayed as the default label as you illustrated in your next button example. 

Do you think a non-editable readonly text input value should fall into ANDI's static value category? 
`<input aria-label=balance type=text value=100  readonly>` "balance readonly 100"

I do understand your reasoning but since you mentioned most screen readers would read the static default value of a text input could it help those newer to accessibility to add the value in these specific input type text use cases to get a real world output simulation?
