### ISSUE TITLE
On some sites, ANDI covers the top of the page.

### ISSUE THREAD

**Issue by a11yJoy** [SSAgov/ANDI#14]
While testing sites, I've noticed that ANDI usually moves the page down which allows the tester to see any issues towards the top of the page. However, there have been several instances where ANDI appears on the page as an overlay and obscures the top of the page, even in mini-mode. This has happened with pages both with and without iFrames.

An example of this occurrence can be seen here: www.stonehill.edu

Please let me know if I can provide additional information.

**Comment by SSAgov** [comment]
Usually this is due to the CSS of the test page (as in your example). ANDI tries to account for position:fixed elements, but sometimes there are overlapping issues due to complex page structure and dynamic/responsive design. In a future update, we will be looking into adding the ability to “pop out” the ANDI Bar allowing it to function as a modal.

**Comment by SSAgovAdmin** [comment]
We have implemented an advanced feature to be able to help when this issue arises. [See the linearize function documentation](https://www.ssa.gov/accessibility/andi/help/howtouse.html#LinearizePage)

**Comment by cliffbert** [comment]
Using the Refresh ANDI button (upper left-ish) moves the content down.
