### ISSUE TITLE
ANDI not detecting body elements in Oracle ADF web application

### ISSUE THREAD

**Issue by PeterBNY** [SSAgov/ANDI#141]
I disabled the Content Security Policy (CSP) and was able to get ANDI to overlay on the following webpage after login:
[https://my.ginniemae.gov/](url)

However, it is only finding the header & banner elements near the top of the page. ANDI detects the rest of the page below as one large element (not able to isolate tables, buttons, input fields, etc.). I have tried both mouse hover and the Next or Previous Element buttons.

Could this behavior be due to the Oracle ADF framework and how its components are built? Please let me know if there is any kind of workaround or solution to get ANDI to properly detect these elements. Thanks in advance.

**Comment by JohnCotterSSA** [comment]
We at SSA are not able to login to this site, but here's some suggestions:

It could be that the content in the "large element" is an iframe. If that's the case, you may need to select iframes from the ANDI modules dropdown to isolate and test the content in the iframe.
[Using ANDI on iframes](https://www.ssa.gov/accessibility/andi/help/modules.html#iANDI)

It could also be that the content is an HTML <canvas> element, in which case, in which case ANDI cannot detect the content because the content is not keyboard accessible.
[ANDI canvas alert](https://www.ssa.gov/accessibility/andi/help/alerts.html?canvas_not_keyboard_accessible)

It could also just be that the large region has no focusable elements, in which case default ANDI would not detect any focusable/tabbable content. Try using Structures ANDI to see if it can detect any headings within the region.

**Comment by PeterBNY** [comment]
Thank you for your response, @JohnCotterSSA! The elements were indeed contained in iframes, so selecting iframes from the ANDI modules to isolate and test the content proved to be the solution. Appreciate your help.

**Comment by JohnCotterSSA** [comment]
Glad I could help! Happy testing.
