### ISSUE TITLE
Incorrect font-size in color contrast module

### ISSUE THREAD

**Issue by carlganz** [SSAgov/ANDI#225]
<img width="902" alt="Font-Size Bug" src="https://github.com/SSAgov/ANDI/assets/11653794/f9aa60c6-1077-46aa-8e3b-89b214a5a5f9">

Hello, I am seeing in ANDI an error for font-size 11px, but when I view the CSS metadata in the browser I see font-size 15px overriding a value of 10px, no 11px in site.  Please advise

**Comment by JohnCotterSSA** [comment]
From your screenshot, it looks like ANDI is reporting a font size of 11pt on the <p> tag. However, you circled 15px from the <body> tag's styles. These are two different elements.

If you want to double check the font size that ANDI is calculating, select the correct element in he DOM (in this case, the <p> element>, then select the "Computed" tab. 
![image](https://github.com/SSAgov/ANDI/assets/55763887/f1fb9756-fc00-4d87-91e8-c81b5eb6c4cc)
Scroll down to find the font-size property and it should show the true, computed font size, which is what ANDI is using.

**Comment by carlganz** [comment]
<img width="906" alt="Font-Size Bug2" src="https://github.com/SSAgov/ANDI/assets/11653794/42f1f59b-3c59-4fa2-baec-567d112d491e">

I'm sorry I'm not following. I'm looking at computed now and have the same `li` element selected across the board. Still seeing different font-sizes

**Comment by JohnCotterSSA** [comment]
Ah, I see. ANDI is reporting on the font pt (point) size, while dev tools displays the px pixel size. That's the reason for the discrepancy you are noticing. Under-the-hood, ANDI uses the computed pixel value for the check since pt sizes are not a good measure of comparison. Font point sizes differ depending on font family. WCAG 1.4.3 define large scale text in points. It's very confusing! So ANDI does the calculation in pixel and then displays pt size to comply with the WCAG large text threshold.

**Comment by fstrr** [comment]
ANDI is showing 11pt, not 11px. If you look at [WCAG's Contrast (Minimum) criterion](https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html#:~:text=When%20evaluating%20this,and%2024px.), it states that pt and px are not equal, and you have to multiply the pt value by 1.333 to get the px value. Therefore: 11pt * 1.333 = 14.663px, which looks to be rounded to 15px in dev tools.

**Comment by carlganz** [comment]
Thank you
