### ISSUE TITLE
the url isn't working and did all the troubleshooting and is not work

### ISSUE THREAD

**Issue by TheodosiaV** [SSAgov/ANDI#229]
I used the followingjavascript:void((function(){andiScript=document.createElement('script');andiScript.setAttribute('src','https://www.ssa.gov/accessibility/andi/andi.js');document.body.appendChild(andiScript)})());

Its not working. Is there a new url

**Comment by JohnCotterSSA** [comment]
It looks correct and hasn't changed. Is it not working on any site? If so, you might not be setting the bookmark correctly. 

You might find it easier to just drag and drop the ANDI bookmarklet into your bookmarks toolbar from [the ANDI install page](https://www.ssa.gov/accessibility/andi/help/install.html) instead of creating it manually.
