### ISSUE TITLE
Customs and Border Protection Lifecycle Date Request ANDI

### ISSUE THREAD

**Issue by CBPSection508Office** [SSAgov/ANDI#24]
Before CBP can purchase/continue to use any software/hardware products we need the manufacture (SSA.GOV) to verify the lifecycle date/extend the lifecycle date (the day you plan on transitioning away from the product).
 
This would be the month day and year of the announced end date to determine when you (SSA.GOV) will be transitioning from ANDI. If you could confirm that you will support ANDI until 9/1/2021 (in an email), or the date month and year you will support ANDI to that would be great. Thank you.

**Comment by SSAgovAdmin** [comment]
Hello friends at CBP, we’re glad you’re using ANDI.  ANDI is used by all of our accessibility testers and many of our developers, and is currently an integral part of our operation.  We are very happy to share it with other agencies and the public.  Because SSA depends on annual appropriations to fund much of our work, we cannot make firm commitments beyond the current fiscal year (i.e. FY 19).   We are supporting and continue developing ANDI at this time.  We also reached out to our counterparts at DHS HQ, and we understand they intend to support ANDI through your requested timeframe should SSA no longer be able to do so.  That’s the beauty of open source.
