### ISSUE TITLE
It may be useful to expose the name attribute for input type radio button so testers can verify radio group correctness

### ISSUE THREAD

**Issue by mraccess77** [SSAgov/ANDI#28]
The name attributes must match for radio button groups to be created correctly to support keyboard navigation.  While the arrow keys can be used to test this it might be useful to include the name attribute in the element shown with ANDI > Focusable elements.

**Comment by SSAgovAdmin** [comment]
Thank you for the suggestion. We understand how this could be useful to a tester or developer. However, we are concerned that adding something called "name" to the AC table in ANDI may be confusing; it might be easy to mix it up with the concept of accessible name. The name attribute of a radio button is programmatic and shouldn't be "exposed" to an end user. 

It's our assumption that testers may find it easiest to simply use the radio buttons (make some selections) to make sure they are operating as normal and grouped properly, rather than compare the name attribute values.

As a compromise, we will add the radio button's index number in its name group. For example: ANDI Output: Favorite Primary Color: red 1 of 3. Screen readers in modern browsers are doing this as well. This will help a tester/dev know if the radio button is associated with others and how many are in the group, but not necessarily which other buttons it is associated with. In addition, if a radio button has some grouping text (as most do - and should) such as a legend, that text currently appears in the Output. A tester could derive which radio buttons go together by comparing the output.

This enhancement will be available in the next ANDI update planned to release within the next two weeks.
