### ISSUE TITLE
Cannot read property 'left' of undefined

### ISSUE THREAD

**Issue by kaylee42** [SSAgov/ANDI#43]
This error pops up in the console for me sometime when I'm using ANDI. 

Stacktrace: 
Uncaught TypeError: Cannot read property 'left' of undefined
    at AndiLaser.drawLaser (andi.js:1565)
    at HTMLAnchorElement.<anonymous> (andi.js:676)
    at HTMLAnchorElement.handle (jquery.min.js:2)
    at HTMLAnchorElement.dispatch (jquery.min.js:2)
    at HTMLAnchorElement.y.handle (jquery.min.js:2)
    at HTMLAnchorElement.sentryWrapped (helpers.ts:77)

Here's what a photo of the line described above from Sentry: 
<img width="806" alt="Code showing error at line 1565:37, code pasted below" src="https://user-images.githubusercontent.com/14985351/56441445-14ddd700-62bb-11e9-80da-b8fe8e242477.png">
```
function AndiLaser(){
	//Draws a laser. Pass in an object containing properties top and left, AKA the result of jQuery offset().
	this.drawLaser = function(fromHereCoords, toHereCoords, targetObject){
		if(browserSupports.svg){
			$("#ANDI508-laser").attr("x1",fromHereCoords.left).attr("y1",fromHereCoords.top)
							   .attr("x2",  toHereCoords.left).attr("y2",  toHereCoords.top);
			$("#ANDI508-laser-container").css("cssText","display:inline !important");
			$(targetObject).addClass("ANDI508-laserTarget");
		}
	};
	//Removes the lasers by hiding the laser container.
```

**Comment by SSAgovAdmin** [comment]
Thank you for your helpful notes.

We were able to reproduce this issue following these steps: Launch ANDI. Alert appears on element A. Something in the page's JavaScript causes element A to be removed from the page. Hold shift and hover over the alert that refers to element A (attempting to draw laser). Error message appears in console because it is trying point laser at something that is gone from the page.

If you were to refresh ANDI after the element went was removed, this error in the console would no longer appear. We remind users that ANDI is not live-scanning the page; the refresh button is helpful to rescan after any dynamic changes occur.

To prevent this console error, we will make a change to check if the targetObject exists before pointing the laser.
