### ISSUE TITLE
ANDI not properly analyzing content

### ISSUE THREAD

**Issue by KristinDOIU** [SSAgov/ANDI#58]
Hi all,

I've just started using ANDI to test a course I've built for the Department of the Interior using Articulate elearning software. As you can see in the screenshot below, cANDI says that I am using dark text on a dark background, when in fact I am using black text on a white background. 

Additionally, ANDI tells me that there is no tab order set on almost every single page, when in fact a tab order is set.

A blind coworker who tests for 508 compatibility using JAWS says no alt text is set when it is. I opened a ticket with Articulate and they are able to read the alt text using JAWS. Because of this, I'm guessing that our browser settings may be interfering or incompatible with Articulate software, and I suspect ANDI is having the same issue. Are there any known issues between ANDI and Articulate? If not, can someone help me understand why ANDI doesn't seem to like my course? Half the time ANDI doesn't even seem to look at the course content, and only looks at the course player, which may or may not be 508 compliant. I've removed as many elements of the player as possible, but ANDI doesn't always seem to look at the content. 

<img width="960" alt="ANDI Question1" src="https://user-images.githubusercontent.com/58826479/70740785-286d0080-1cd7-11ea-8d96-c4d5e352dbea.png">

A draft of the course can be seen here: https://360.articulate.com/review/content/f68aa881-8213-452c-b14c-56babda5e9ef/review

Thanks all,

Kristin Hatcher
DOI University
734-834-7806
kristin_hatcher@ios.doi.gov

**Comment by JohnCotterSSA** [comment]
Hi Kristen, Thanks for the sample link. 

I don't recall any ANDI alerts about "no tab order being set". Do you mean when you press the tab order button, you don't see any flags show up? That is probably because the majority of the content on this page is nested within iframes. To test content within iframes using ANDI, you need to select "iframes" from the module dropdown. Then the "test in new tab" button, then relaunch ANDI. I was able to successfully do that using the link you've provided.

As for your issue with cANDI, that is a known issue that sometimes occurs when the foreground element containing text has been re-positioned on the page using CSS and is set on top of an element that is not an ancestor of the foreground element. I'm not sure how to navigate to the screenshot you've provided to additionally troubleshoot the issue.

As for your issue with alt text not being detected, can you provide more information about the specific element on your site?

**Comment by KristinDOIU** [comment]
Hi John, 

Thanks for your response. I will switch to iFrames, but I’m afraid I’m not sure how to do that. You say to select “iframes” from the module dropdown, but if this is the module dropdown you mean, I don’t see iframes here. I did look within each module to see if there was a way to switch to iframes, but did not find it. I see it in the help, along with a couple of other modules I don’t have, and I went back to the detailed installation instructions, but found nothing there that I may have done wrong. I’m using Google Chrome.  

![image](https://user-images.githubusercontent.com/58826479/72358172-5ca65900-36a9-11ea-9eb9-e30dd88c68b0.png)

Thank you for the information about cANDI. Unfortunately, I am not in control of the CSS built by the course software, so I will verify the colors meet the 508 and WCAG requirements by using WebAIM. 

It looks like the issues with the alt text has mostly been resolved; both my tester and ANDI are able to see the alt text now. Perhaps it was a problem in my output.

Thanks for any help you can provide me.

**Comment by JohnCotterSSA** [comment]
You're welcome, Kristin.

The iframes and tables modules only appear in the dropdown when those elements are detected at launch of ANDI. In the link provided, I was able to launch ANDI, and I saw the iframes option in the list.
