### ISSUE TITLE
TABINDEX errors

### ISSUE THREAD

**Issue by lkoss** [SSAgov/ANDI#84]
I am using ANDI against an Oracle APEX 20.1 application. On the left side we have the Navigation Menu that is auto generated by Oracle. ANDI is giving errors when inspecting the elements show they are not. Is this a bug in ANDI?

I attached a document that includes screen shots of the different issues I found and if I can fix them. I think some issues involving the tabindex=-1 may need to be addressed with Oracle. If so, then I'll inform my Agency to contact Oracle Support.

[ANDI 508 Issues.docx](https://github.com/SSAgov/ANDI/files/5424548/ANDI.508.Issues.docx)

**Comment by JohnCotterSSA** [comment]
Hi There. Can you please post the screen shots directly to the github comments? We don't want to download docx files for security reasons. Thank you!

**Comment by lkoss** [comment]
If I load it as a PDF be better? Otherwise I'll try post the screen shots. I can send the doc or PDF from my epa.gov account if that if satisfy the security issue.

**Comment by JohnCotterSSA** [comment]
Screenshots would be great. Sorry for any inconvenience.

**Comment by lkoss** [comment]
![image](https://user-images.githubusercontent.com/55795761/96911347-5b8b2f00-1466-11eb-9cd1-27a356e2ba11.png)
This are links generated by Oracle for the Navigation Menu. 
ANDI is saying that the tabindex is -1.
![image](https://user-images.githubusercontent.com/55795761/96911381-65149700-1466-11eb-9688-b23c3d418f78.png)
When inspecting the element, it is showing a tabindex="0". Even adding the tabindex="0" to the Navigation Item it still shows up -1 in ANDI.
![image](https://user-images.githubusercontent.com/55795761/96911462-7cec1b00-1466-11eb-8e4e-98cee01d4562.png)
![image](https://user-images.githubusercontent.com/55795761/96911541-9725f900-1466-11eb-908f-7423d6f02135.png)
The link is auto generated by Oracle and includes the alt attribute. Cannot override it.
Inspecting the element
![image](https://user-images.githubusercontent.com/55795761/96911569-a016ca80-1466-11eb-854b-509fede22662.png)
Misuses of Label Tag: (2)
Tab Order Alerts: (7)
![image](https://user-images.githubusercontent.com/55795761/96911705-d18f9600-1466-11eb-9ced-15548719ae52.png)
Explicit <label[for]> only works with form elements. 
Focusable element is not in keyboard tab order; should it be tabbable?
Two fields have this. This one is checkboxes and the other is Radio Buttons.
The form is auto generated by Oracle. The fields are within the <form> tags.
![image](https://user-images.githubusercontent.com/55795761/96911768-e835ed00-1466-11eb-9bf8-c3c3aa2c0088.png)
ANDI also suggests "Consider using aria-label or aria-labelledby on the element." Note they have the aria-labelledby.
![image](https://user-images.githubusercontent.com/55795761/96911796-f421af00-1466-11eb-95eb-bc265fae26f9.png)

Here are some. Also I have an interactive grid which Oracle APEX generates the code. I'm getting Focusable element is not in keyboard tab order; should it be tabbable? errors.
These are hidden spots that Oracle uses. I'm confused. If it's hidden then it's not to be seen or used by a sighted or unsighted person. So why is that an error.

Hope this upload works?

**Comment by JohnCotterSSA** [comment]
Thank you for copying the screen shots. I'm going to try to number these issues:

1)
For the issue relating to ANDI reporting a different tabindex than the dom explorer. What is most likely going on here is that there is a roving tabindex concept. In other words, the zero value is moving around. So at the moment you hit ANDI, things were set. Then you navigated the menu, JavaScript moved the tabindexes around and ANDI wasn't refreshed.

A negative tabindex is not always a problem. But when ANDI detects it, it alerts the tester to do additional manual inspection. For more information, take a look at [the help page for this alert](https://www.ssa.gov/accessibility/andi/help/alerts.html#not_in_tab_order).

2)
I may not fully understand the description about the issue about the alt text. I'm assuming ANDI is throwing the alert about alt being only for images. In this instance you can ignore that alert if the ANDI output is sufficient for the element. I assume the output would be "download" which should be sufficient.

3)
I would need to see more information about the issue relating to checkboxes and radio buttons. Those are two element types where a negative tabindex could be an accessibility issue. Again, ANDI flagged it to encourage the tester to perform additional manual inspection. In other words, try to tab to the elements using a keyboard.

4)
For the role=group element, I don't see ANDI making that suggestion based on the screen shot.

5)
For the grid structure, it's a similar thing: ANDI threw the alert about the negative tabindex so that the tester will perform additional manual testing to evaluate whether there are keyboard access issues.
