### ISSUE TITLE
ANDI does not have a mode that shows content marked with ARIA live regions

### ISSUE THREAD

**Issue by mraccess77** [SSAgov/ANDI#9]
A mode that shows content marked with ARIA live regions can be helpful to determine when ARIA live regions are used on the page without using assistive technology.

**Comment by SSAgov** [comment]
This feature will be coming soon in a future release

**Comment by SSAgov** [comment]
The ability to detect aria-live regions has been added to sANDI (Structures) using the “role attributes” button. When role=alert exists on an element, if the element also has aria-live, it will appear on the overlay flag.

**Comment by mraccess77** [comment]
Thanks.  I see the ARIA roles option working with aria role alert.  However, I don't see aria-live working.  I'm not sure what is meant by overlay flag but I was looking in the structure module > ARIA role attributes.
Go to https://labs.levelaccess.com/index.php/ARIA_Live
Activate the button to show the aria-live region
Use ANDI structure module > aria role attributes.

**Comment by SSAgov** [comment]
Thank you for the test page. It wasn’t known to our dev team that aria-live works successfully without role=alert. Therefore, in order to provide proper detection, a new Mode “live regions” has been added to sANDI (structures) module. Selecting the button will allow users to inspect elements that have any of the following: role=alert, role=status, aria-live=polite, aria-live=assertive. When the live region is updated by the application, refreshing ANDI (alt + =) will display any change to the region’s Output. Since aria-live is not dependent on role=alert, aria-live detection has been removed from the “role attributes” overlay.

**Comment by mraccess77** [comment]
Thanks!  In particular ARIA role of alert can be dangerous as it may cause screen readers to announce content from non-active tabs.
