### ISSUE TITLE
allVisibleElements in sections like sandi.js, ... should be changed to allElements with filters like in handi.js

### ISSUE THREAD

**Issue by ollie-iterators** [SSAgov/ANDI#93]
I think that ANDI might work better if the code that determines which elements to check on a page was changed for the modules in the code areas candi.js, fandi.js, gandi.js, iandi.js, landi.js, sandi.js, tandi.js from using TestPageData.allVisibleElements to using TestPageData.allElements with filters (if necessary) to exclude areas that are not supposed to be tested in the section that is being analyzed like it is done in the handi.js module for hidden content.

I think it would improve things for various reasons:
1.  It would allow people using ANDI to have an easier way to find out the number of certain types of elements on the page like links, headers
       a. As an example, on https://www.boston.gov/, there is a button marked Translate. When the button is not clicked, ANDI says that there are 110 links on the page. When the button is clicked, ANDI says that there are 224 links on the page.
2. If someone is going to mention that those links, buttons, etc. are not visible on the page, then I would say that it could be nice to have some condition to separate the elements that are clearly visible on the page from the elements that are not seen on the page when the page is first loaded (This is described in the note I put into 1a, above).
3. Sometimes there are issues with ANDI appearing on the top of the page. If something is pressed that shows an element that was not visible when the page was loaded, then the element that was put on the page could intersect with ANDI making it harder for the element to be quit from. An example if this is what happens when the Translate button is pressed on https://boston.gov. I have attached a video below that shows the issue:
[2021 03 02, Sometimes there are issues with ANDI appearing on the top of the site.mp4.zip](https://github.com/SSAgov/ANDI/files/6070218/2021.03.02.Sometimes.there.are.issues.with.ANDI.appearing.on.the.top.of.the.site.mp4.zip)

**Comment by JohnCotterSSA** [comment]
Thank you for the suggestion and your interest in ANDI. 

ANDI is used during a manual test process. The need to refresh ANDI based on on-screen changes is needed during that process. If ANDI were to report issues with elements that are not visible on screen, it would confuse ANDI users and would raise many false positive issues. ANDI is able to detect elements that a screen reader should detect, even if the elements are placed off screen. However, when elements are hidden from sighted users and screen readers, then ANDI ignores the elements, until they are placed into "view".

In regards to the number 3 above, that is a known display issue that is caused by ANDI's height needing to flex to adapt to the information it contains depending on the element. We are considering redesigning ANDI to make it appear on the left side of a test page instead of above. This would resolve vertical overlapping issues. For now, using ANDI's "arrow buttons", AKA the next/prev element buttons, should cause ANDI's height to adjust and not overlap test page content.
